name: mtax24
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.1.10+10544

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  get_it: ^7.1.3
  get_it_mixin: ^3.1.1
  keyboard_dismisser: ^2.0.0
  flutter_screenutil: ^5.0.0+2
  device_info: ^2.0.0
  fluttertoast: ^8.0.7
  rxdart: ^0.27.0
  easy_localization: ^3.0.0
  shared_preferences: ^2.0.6
  flutter_phoenix: ^1.0.0
  local_auth:
  flutter_share: ^2.0.0
  encrypt: ^5.0.0
  open_file_safe: ^3.2.3
  path_provider: ^2.0.0
  flutter_html: ^0.11.1
  get: ^4.1.4
  flutter_svg: ^0.22.0
  flutter_local_notifications: ^11.0.0
  package_info: ^2.0.0
  dio: ^3.0.10
  retrofit: ^1.3.4+1
  firebase_core: ^2.12.0
  firebase_messaging: ^14.3.0
  flutter_native_splash: ^1.2.0
  store_redirect: ^2.0.0
  external_path: ^1.0.3
  permission_handler: ^11.0.0
  flutter_speed_dial: ^2.1.1
  vietnamese_number_reader: ^1.0.0
  translator: ^0.1.5
  qr_code_scanner: ^1.0.1
  url_launcher: ^6.0.3
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  build_runner: any
  flutter_launcher_icons: "^0.9.0"

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon_app/icon.jpeg"

flutter:

  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/icon_app/
    - assets/json/menu/
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
